MISTAKE_SICKERS = ['CAADAgADBAAD4MksBLZr4yxPGXSTAg', 'CAADAgADBQAD4MksBKQTvaJcwBj9Ag', 'CAADAgADBgAD4MksBMZTgUc3RQ8VAg',
                    'CAADAgADBwAD4MksBPIDLy24--fIAg', 'CAADAgADCAAD4MksBPJevrHhHta9Ag', 'CAADAgADCQAD4MksBFBGkYiK5bT_Ag',
                    'CAADAgADCgAD4MksBIUR9n4CaQmSAg', 'CAADAgADCwAD4MksBISJfx_z2ow2Ag', 'CAADAgADDAAD4MksBARIcGLFGwIEAg',
                    'CAADAgADDQAD4MksBKpHNerXrk3NAg']
LOSE_STICKER = 'CAADAgADDgAD4MksBPkL9qe6Lra8Ag'



